
  CREATE TABLE "LBD01_VINCULO_USP" 
   (	"NROUSP" NUMBER(7,0), 
	"TIPOVINC" NUMBER(1,0) NOT NULL ENABLE, 
	"NOME" VARCHAR2(100) NOT NULL ENABLE, 
	"DATAINGRESSO" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"DATANASCIMENTO" DATE, 
	"ATIVO" CHAR(1) DEFAULT 'y', 
	 CONSTRAINT "CK_VINCULO_USP" CHECK (TipoVinc IN (1, 2, 3)) ENABLE, 
	 CONSTRAINT "CK_ATIVO" CHECK (Ativo IN ('y','n')) ENABLE, 
	 CONSTRAINT "PK_LBDVINCULO_USP" PRIMARY KEY ("NROUSP") ENABLE
   ) ;
 

  CREATE TABLE "LBD02_PROFESSOR" 
   (	"NROUSP" NUMBER(7,0), 
	"TITULACAO" VARCHAR2(9) DEFAULT 'Doutorado' NOT NULL ENABLE, 
	"PREDIO" NUMBER(2,0), 
	"SALA" NUMBER(2,0), 
	 CONSTRAINT "CK_TITULACAO" CHECK (Titulacao IN ('Mestrado','Doutorado')) ENABLE, 
	 CONSTRAINT "PK_LBDPROFESSOR" PRIMARY KEY ("NROUSP") ENABLE, 
	 CONSTRAINT "FK_LBDPROFESSOR_NROUSP" FOREIGN KEY ("NROUSP")
	  REFERENCES "LBD01_VINCULO_USP" ("NROUSP") ON DELETE CASCADE ENABLE
   ) ;
 

  CREATE TABLE "LBD03_ALUNO" 
   (	"NROUSP" NUMBER(7,0), 
	"IDADE" NUMBER(2,0), 
	"CIDADENASC" VARCHAR2(50), 
	"ESTADO" VARCHAR2(2), 
	 CONSTRAINT "CK_IDADE" CHECK (Idade > 10) ENABLE, 
	 CONSTRAINT "PK_LBDALUNO" PRIMARY KEY ("NROUSP") ENABLE, 
	 CONSTRAINT "FK_LBDALUNO_NROUSP" FOREIGN KEY ("NROUSP")
	  REFERENCES "LBD01_VINCULO_USP" ("NROUSP") ON DELETE CASCADE ENABLE
   ) ;
 

  CREATE TABLE "LBD04_FUNCIONARIO" 
   (	"NROUSP" NUMBER(7,0), 
	"NIVEL" VARCHAR2(8) DEFAULT 'Basico' NOT NULL ENABLE, 
	"LOTACAO" VARCHAR2(5) DEFAULT 'ICMC' NOT NULL ENABLE, 
	 CONSTRAINT "CK_NIVEL" CHECK (Nivel IN ('Basico', 'Tecnico', 'Superior')) ENABLE, 
	 CONSTRAINT "CK_LOTACAO" CHECK (Lotacao IN ('ICMC', 'EESC', 'IQSC', 'IFSC')) ENABLE, 
	 CONSTRAINT "PK_LBDFUNCIONARIO" PRIMARY KEY ("NROUSP") ENABLE, 
	 CONSTRAINT "FK_LBDFUNCION_NROUSP" FOREIGN KEY ("NROUSP")
	  REFERENCES "LBD01_VINCULO_USP" ("NROUSP") ON DELETE CASCADE ENABLE
   ) ;
 

  CREATE TABLE "LBD05_DISCIPLINA" 
   (	"COD" VARCHAR2(7), 
	"NOME" VARCHAR2(100) NOT NULL ENABLE, 
	"EMENTA" CLOB, 
	 CONSTRAINT "PK_LBDDISCIPLINA" PRIMARY KEY ("COD") ENABLE
   ) ;
 

  CREATE TABLE "LBD06_LECIONA" 
   (	"NROUSPPROF" NUMBER(7,0), 
	"CODDISC" VARCHAR2(7), 
	 CONSTRAINT "PK_LBDLECIONA" PRIMARY KEY ("NROUSPPROF", "CODDISC") ENABLE, 
	 CONSTRAINT "FK_LBDLECIONA_PROF" FOREIGN KEY ("NROUSPPROF")
	  REFERENCES "LBD02_PROFESSOR" ("NROUSP") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "FK_LBDLECIONA_DISC" FOREIGN KEY ("CODDISC")
	  REFERENCES "LBD05_DISCIPLINA" ("COD") ON DELETE CASCADE ENABLE
   ) ;
 

  CREATE TABLE "LBD07_TURMA" 
   (	"NROTURMA" NUMBER(6,0), 
	"ANO" NUMBER(4,0), 
	"CODDISC" VARCHAR2(7), 
	"NROUSPPROF" NUMBER(7,0) NOT NULL ENABLE, 
	 CONSTRAINT "PK_LBDTURMA" PRIMARY KEY ("NROTURMA", "ANO", "CODDISC") ENABLE, 
	 CONSTRAINT "FK_LBDTURMA_DISC" FOREIGN KEY ("CODDISC")
	  REFERENCES "LBD05_DISCIPLINA" ("COD") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "FK_LBDTURMA_PROF" FOREIGN KEY ("NROUSPPROF")
	  REFERENCES "LBD02_PROFESSOR" ("NROUSP") ENABLE
   ) ;
 

  CREATE TABLE "LBD08_MATRICULA" 
   (	"NROUSP" NUMBER(7,0), 
	"CODDISC" VARCHAR2(7), 
	"ANO" NUMBER(4,0) NOT NULL ENABLE, 
	"NROTURMA" NUMBER(6,0) NOT NULL ENABLE, 
	"NOTA" NUMBER(4,2), 
	 CONSTRAINT "PK_LBDMATRICULA" PRIMARY KEY ("NROUSP", "CODDISC", "ANO") ENABLE, 
	 CONSTRAINT "FK_LBDMATRICULA_VINCULADO" FOREIGN KEY ("NROUSP")
	  REFERENCES "LBD01_VINCULO_USP" ("NROUSP") ENABLE, 
	 CONSTRAINT "FK_LBDMATRICULA_TURMA" FOREIGN KEY ("NROTURMA", "ANO", "CODDISC")
	  REFERENCES "LBD07_TURMA" ("NROTURMA", "ANO", "CODDISC") ENABLE
   ) ;
 

  CREATE TABLE "LBD09_CURSO_ELETRONICO" 
   (	"CODCURSO" VARCHAR2(7), 
	"NROTURMA" NUMBER(6,0) NOT NULL ENABLE, 
	"ANO" NUMBER(4,0) NOT NULL ENABLE, 
	"CODDISC" VARCHAR2(7) NOT NULL ENABLE, 
	"ACEITAEXTERNOS" CHAR(1) DEFAULT 'y', 
	 CHECK (AceitaExternos IN ( 'y', 'n' )) ENABLE, 
	 CONSTRAINT "PK_LBDCURSO_ELETRONICO" PRIMARY KEY ("CODCURSO") ENABLE, 
	 CONSTRAINT "UN_CURSO_ELETRONICO" UNIQUE ("NROTURMA", "CODDISC") ENABLE, 
	 CONSTRAINT "FK_LBDCURSO_ELETRONICO_TURMA" FOREIGN KEY ("NROTURMA", "ANO", "CODDISC")
	  REFERENCES "LBD07_TURMA" ("NROTURMA", "ANO", "CODDISC") ON DELETE CASCADE ENABLE
   ) ;
 

  CREATE TABLE "LBD10_PARTICIPANTE" 
   (	"CODCURSO" VARCHAR2(7), 
	"NROUSP" NUMBER(7,0), 
	"NOTA" NUMBER(4,2), 
	"NOTAFINAL" NUMBER(4,2), 
	 CONSTRAINT "PK_LBDPARTICIPANTE" PRIMARY KEY ("CODCURSO", "NROUSP") ENABLE, 
	 CONSTRAINT "FK_LBDPARTICIPANTE_CURSO" FOREIGN KEY ("CODCURSO")
	  REFERENCES "LBD09_CURSO_ELETRONICO" ("CODCURSO") ENABLE, 
	 CONSTRAINT "FK_LBDPARTICIPANTE_VINC" FOREIGN KEY ("NROUSP")
	  REFERENCES "LBD01_VINCULO_USP" ("NROUSP") ENABLE
   ) ;
 

  CREATE TABLE "LBD11_GRUPO" 
   (	"NROGRUPO" NUMBER(2,0), 
	"CODCURSO" VARCHAR2(7), 
	"NOMEGRUPO" VARCHAR2(100), 
	 CONSTRAINT "PK_LBDGRUPO" PRIMARY KEY ("NROGRUPO", "CODCURSO") ENABLE, 
	 CONSTRAINT "FK_LBDGRUPO" FOREIGN KEY ("CODCURSO")
	  REFERENCES "LBD09_CURSO_ELETRONICO" ("CODCURSO") ON DELETE CASCADE ENABLE
   ) ;
 

  CREATE TABLE "LBD12_COMPOE_GRUPO" 
   (	"CODCURSO" VARCHAR2(7), 
	"NROUSP" NUMBER(7,0), 
	"NROGRUPO" NUMBER(2,0) NOT NULL ENABLE, 
	 CONSTRAINT "PK_LBDCOMPOE_GRUPO" PRIMARY KEY ("NROUSP", "CODCURSO") ENABLE, 
	 CONSTRAINT "FK_LBDCOMPOE_GRUPO_GRUPO" FOREIGN KEY ("NROGRUPO", "CODCURSO")
	  REFERENCES "LBD11_GRUPO" ("NROGRUPO", "CODCURSO") ENABLE, 
	 CONSTRAINT "FK_LBDCOMPOE_GRUPO_PARTIC" FOREIGN KEY ("CODCURSO", "NROUSP")
	  REFERENCES "LBD10_PARTICIPANTE" ("CODCURSO", "NROUSP") ENABLE
   ) ;
 

  CREATE TABLE "LBD13_TRABALHO" 
   (	"NROTRABALHO" NUMBER(2,0), 
	"CODCURSO" VARCHAR2(7), 
	"DESCRICAO" CLOB, 
	"ARQUIVOESPEC" BLOB, 
	"DATAHORALIMITE" DATE, 
	 CONSTRAINT "PK_LBDTRABALHO" PRIMARY KEY ("NROTRABALHO", "CODCURSO") ENABLE, 
	 CONSTRAINT "FK_LBDTRABALHO_CURSO" FOREIGN KEY ("CODCURSO")
	  REFERENCES "LBD09_CURSO_ELETRONICO" ("CODCURSO") ON DELETE CASCADE ENABLE
   ) ;
 

  CREATE TABLE "LBD14_ENTREGA_TRABALHO" 
   (	"NROTRABALHO" NUMBER(2,0), 
	"NROGRUPO" NUMBER(2,0), 
	"CODCURSO" VARCHAR2(7), 
	"DATAHORARIOENTREGA" DATE NOT NULL ENABLE, 
	"ARQUIVO" BLOB, 
	"NOTA" NUMBER(4,2), 
	 CONSTRAINT "PK_LBDENTREGA_TRABALHO" PRIMARY KEY ("NROTRABALHO", "NROGRUPO", "CODCURSO") ENABLE, 
	 CONSTRAINT "FK_LBDENTREGA_TRAB_TRAB" FOREIGN KEY ("NROTRABALHO", "CODCURSO")
	  REFERENCES "LBD13_TRABALHO" ("NROTRABALHO", "CODCURSO") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "FK_LBDENTREGA_TRAB_GR" FOREIGN KEY ("NROGRUPO", "CODCURSO")
	  REFERENCES "LBD11_GRUPO" ("NROGRUPO", "CODCURSO") ON DELETE CASCADE ENABLE
   ) ;
 

  CREATE TABLE "LBD15_TIPO_RECURSO" 
   (	"CODTIPO" VARCHAR2(3), 
	"NOME" VARCHAR2(100) NOT NULL ENABLE, 
	"DESCRICAO" VARCHAR2(300), 
	"REQUISITOS" VARCHAR2(200), 
	 CONSTRAINT "PK_LBDTIPO_RECURSO" PRIMARY KEY ("CODTIPO") ENABLE, 
	 CONSTRAINT "UN_TIPO_RECURSO_NOME" UNIQUE ("NOME") ENABLE
   ) ;
 

  CREATE TABLE "LBD16_RECURSO_ELETRONICO" 
   (	"NRORECURSO" NUMBER(3,0), 
	"CODCURSO" VARCHAR2(7), 
	"TIPO" VARCHAR2(3) NOT NULL ENABLE, 
	"NOME" VARCHAR2(100) NOT NULL ENABLE, 
	"DESCRICAO" VARCHAR2(300), 
	"ARQUIVORECURSO" BLOB, 
	 CONSTRAINT "PK_LBDRECURSO_ELETRONICO" PRIMARY KEY ("NRORECURSO", "CODCURSO") ENABLE, 
	 CONSTRAINT "UN_RECURSO_ELETRONICO_NOME" UNIQUE ("NOME", "CODCURSO") ENABLE, 
	 CONSTRAINT "FK_LBDREC_ELETR_CURSO" FOREIGN KEY ("CODCURSO")
	  REFERENCES "LBD09_CURSO_ELETRONICO" ("CODCURSO") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "FK_LBDREC_ELETR_TIPO" FOREIGN KEY ("TIPO")
	  REFERENCES "LBD15_TIPO_RECURSO" ("CODTIPO") ENABLE
   ) ;
 

  CREATE TABLE "LBD17_LOG_ACESSO" 
   (	"CODLOG" NUMBER(6,0), 
	"DATAHORARIOACESSO" DATE NOT NULL ENABLE, 
	"NROUSP" NUMBER(7,0) NOT NULL ENABLE, 
	"CODCURSO" VARCHAR2(7) NOT NULL ENABLE, 
	"NRORECURSO" NUMBER(3,0) NOT NULL ENABLE, 
	 CONSTRAINT "PK_LBDLOG_ACESSO" PRIMARY KEY ("CODLOG") ENABLE, 
	 CONSTRAINT "FK_LBDLOG_ACESSO_RECURSO" FOREIGN KEY ("NRORECURSO", "CODCURSO")
	  REFERENCES "LBD16_RECURSO_ELETRONICO" ("NRORECURSO", "CODCURSO") ENABLE, 
	 CONSTRAINT "FK_LBDLOG_ACESSO_VINCULADO" FOREIGN KEY ("CODCURSO", "NROUSP")
	  REFERENCES "LBD10_PARTICIPANTE" ("CODCURSO", "NROUSP") ENABLE
   ) ;
 

  CREATE TABLE "LBD18_MENSAGEM" 
   (	"NROMENSAGEM" NUMBER(4,0), 
	"CODCURSO" VARCHAR2(7), 
	"NROUSP" NUMBER(7,0), 
	"TITULO" VARCHAR2(100) NOT NULL ENABLE, 
	"TEXTO" VARCHAR2(500) NOT NULL ENABLE, 
	"DATAHORAPOSTAGEM" DATE NOT NULL ENABLE, 
	 CONSTRAINT "PK_LBDMENSAGEM" PRIMARY KEY ("NROMENSAGEM", "CODCURSO", "NROUSP") ENABLE, 
	 CONSTRAINT "FK_LBDMENSAGEM_PARTIC" FOREIGN KEY ("CODCURSO", "NROUSP")
	  REFERENCES "LBD10_PARTICIPANTE" ("CODCURSO", "NROUSP") ENABLE
   ) ;
 
