
  CREATE TABLE "F01_ESTADO" 
   (	"SIGLA" CHAR(2), 
	"ESTADO" VARCHAR2(100) NOT NULL ENABLE, 
	 CONSTRAINT "PK_ESTADO" PRIMARY KEY ("SIGLA") ENABLE, 
	 CONSTRAINT "UN_ESTADO" UNIQUE ("ESTADO") ENABLE
   ) ;
 

  CREATE TABLE "F02_CIDADE" 
   (	"CIDADE" VARCHAR2(100), 
	"SIGLAC" CHAR(2), 
	 CONSTRAINT "PK_CIDADE" PRIMARY KEY ("CIDADE", "SIGLAC") ENABLE, 
	 CONSTRAINT "FK_CIDADE_ESTADO" FOREIGN KEY ("SIGLAC")
	  REFERENCES "F01_ESTADO" ("SIGLA") ENABLE
   ) ;
 

  CREATE TABLE "F03_TECNICO" 
   (	"CPFT" NUMBER(8,0), 
	"TECNICO" VARCHAR2(100) NOT NULL ENABLE, 
	 CONSTRAINT "PK_TECNICO" PRIMARY KEY ("CPFT") ENABLE, 
	 CONSTRAINT "UN_TECNICO" UNIQUE ("TECNICO") ENABLE
   ) ;
 

  CREATE TABLE "F04_TIME" 
   (	"TTIME" VARCHAR2(100), 
	"ANOFUNDACAO" NUMBER(4,0), 
	"CIDADE" VARCHAR2(100) NOT NULL ENABLE, 
	"ESTADO" CHAR(2) NOT NULL ENABLE, 
	"CPFT" NUMBER(8,0), 
	 CONSTRAINT "PK_TIME" PRIMARY KEY ("TTIME") ENABLE, 
	 CONSTRAINT "FK_TIME_CIDADE" FOREIGN KEY ("CIDADE", "ESTADO")
	  REFERENCES "F02_CIDADE" ("CIDADE", "SIGLAC") ENABLE, 
	 CONSTRAINT "FK_TIME_TECNICO" FOREIGN KEY ("CPFT")
	  REFERENCES "F03_TECNICO" ("CPFT") ENABLE
   ) ;
 

  CREATE TABLE "F05_JOGADOR" 
   (	"CPFJ" NUMBER(8,0), 
	"JOGADOR" VARCHAR2(100) NOT NULL ENABLE, 
	"POSICAO" VARCHAR2(40), 
	"TTIMEJ" VARCHAR2(100), 
	 CONSTRAINT "CH_JOGADOR" CHECK (POSICAO IN ('GOLEIRO', 'ZAGUEIRO', 'LATERAL', 'MEIO-CAMPO', 'ATACANTE')) ENABLE, 
	 CONSTRAINT "PK_JOGADOR" PRIMARY KEY ("CPFJ") ENABLE, 
	 CONSTRAINT "UN_JOGADOR" UNIQUE ("JOGADOR") ENABLE, 
	 CONSTRAINT "FK_JOGADOR_TIME" FOREIGN KEY ("TTIMEJ")
	  REFERENCES "F04_TIME" ("TTIME") ON DELETE SET NULL ENABLE
   ) ;
 

  CREATE TABLE "F06_PATROCINADOR" 
   (	"IDPAT" NUMBER(2,0), 
	"PATROCINADOR" VARCHAR2(100) NOT NULL ENABLE, 
	"SLOGAN" VARCHAR2(200), 
	 CONSTRAINT "PK_PATROCINADOR" PRIMARY KEY ("IDPAT") ENABLE, 
	 CONSTRAINT "UN_PATROCINADOR" UNIQUE ("PATROCINADOR") ENABLE
   ) ;
 

  CREATE TABLE "F07_ARBITRO" 
   (	"CPFA" NUMBER(8,0), 
	"ARBITRO" VARCHAR2(100) NOT NULL ENABLE, 
	 CONSTRAINT "PK_ARBITRO" PRIMARY KEY ("CPFA") ENABLE, 
	 CONSTRAINT "UN_ARBITRO" UNIQUE ("ARBITRO") ENABLE
   ) ;
 

  CREATE TABLE "F08_CAMPEONATO" 
   (	"IDCAMPEONATO" NUMBER(2,0), 
	"CAMPEONATO" VARCHAR2(100) NOT NULL ENABLE, 
	"ANO" NUMBER(4,0) NOT NULL ENABLE, 
	 CONSTRAINT "PK_CAMPEONATO" PRIMARY KEY ("IDCAMPEONATO") ENABLE, 
	 CONSTRAINT "UN_CAMPEONATO" UNIQUE ("CAMPEONATO", "ANO") ENABLE
   ) ;
 

  CREATE TABLE "F09_ESTADIO" 
   (	"IDESTADIO" NUMBER(2,0), 
	"ESTADIO" VARCHAR2(100), 
	"CIDADE" VARCHAR2(100) NOT NULL ENABLE, 
	"ESTADO" CHAR(2) NOT NULL ENABLE, 
	"CAPACIDADE" NUMBER(6,0), 
	 CONSTRAINT "PK_ESTADIO" PRIMARY KEY ("IDESTADIO") ENABLE, 
	 CONSTRAINT "UN_ESTADIO" UNIQUE ("ESTADIO") ENABLE, 
	 CONSTRAINT "FK_ESTADIO_CIDADE" FOREIGN KEY ("CIDADE", "ESTADO")
	  REFERENCES "F02_CIDADE" ("CIDADE", "SIGLAC") ENABLE
   ) ;
 

  CREATE TABLE "F10_EMISSORA" 
   (	"IDEMISSORA" NUMBER(2,0), 
	"EMISSORA" VARCHAR2(100), 
	"TIPO" CHAR(1) NOT NULL ENABLE, 
	"FREQUENCIA" NUMBER(4,1), 
	"CANAL" NUMBER(3,0), 
	"CUSTO_MINUTO" NUMBER(10,2), 
	 CONSTRAINT "CH_EMISSORA" CHECK (
  (TIPO = 'R' AND FREQUENCIA IS NOT NULL)
   OR
  (TIPO = 'T' AND CANAL IS NOT NULL)
 ) ENABLE, 
	 CONSTRAINT "PK_EMISSORA" PRIMARY KEY ("IDEMISSORA") ENABLE, 
	 CONSTRAINT "UN_EMISSORA" UNIQUE ("EMISSORA") ENABLE
   ) ;
 

  CREATE TABLE "F11_PARTIDA" 
   (	"IDPARTIDA" NUMBER(4,0), 
	"TTIME1" VARCHAR2(100) NOT NULL ENABLE, 
	"TTIME2" VARCHAR2(100) NOT NULL ENABLE, 
	"DATAHORA" DATE NOT NULL ENABLE, 
	"IDCAMPEONATOP" NUMBER(2,0) NOT NULL ENABLE, 
	"IDESTADIOP" NUMBER(2,0) NOT NULL ENABLE, 
	"GOLS_TIME1" NUMBER(2,0) DEFAULT 0 NOT NULL ENABLE, 
	"GOLS_TIME2" NUMBER(2,0) DEFAULT 0 NOT NULL ENABLE, 
	 CONSTRAINT "PK_PARTIDA" PRIMARY KEY ("IDPARTIDA") ENABLE, 
	 CONSTRAINT "UN_PARTIDA" UNIQUE ("TTIME1", "TTIME2", "DATAHORA") ENABLE, 
	 CONSTRAINT "FK_TTIME1" FOREIGN KEY ("TTIME1")
	  REFERENCES "F04_TIME" ("TTIME") ENABLE, 
	 CONSTRAINT "FK_TTIME2" FOREIGN KEY ("TTIME2")
	  REFERENCES "F04_TIME" ("TTIME") ENABLE, 
	 CONSTRAINT "FK_PARTIDA_CAMP" FOREIGN KEY ("IDCAMPEONATOP")
	  REFERENCES "F08_CAMPEONATO" ("IDCAMPEONATO") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "FK_PARTIDA_ESTAD" FOREIGN KEY ("IDESTADIOP")
	  REFERENCES "F09_ESTADIO" ("IDESTADIO") ON DELETE SET NULL ENABLE
   ) ;
 

  CREATE TABLE "F12_PATROCINA" 
   (	"IDPAT" NUMBER(2,0), 
	"TTIME" VARCHAR2(100), 
	"CONTRATO" BLOB, 
	"INICIO_VIGENCIA" NUMBER(4,0), 
	"TEMPO_VIGENCIA" NUMBER(3,0), 
	 CONSTRAINT "PK_PATROCINA" PRIMARY KEY ("IDPAT", "TTIME") ENABLE, 
	 CONSTRAINT "FK_PATROCINA_PAT" FOREIGN KEY ("IDPAT")
	  REFERENCES "F06_PATROCINADOR" ("IDPAT") ENABLE, 
	 CONSTRAINT "FK_PATROCINA_TIME" FOREIGN KEY ("TTIME")
	  REFERENCES "F04_TIME" ("TTIME") ENABLE
   ) ;
 

  CREATE TABLE "F13_APITA" 
   (	"CPFA" NUMBER(8,0), 
	"IDPARTIDA" NUMBER(4,0), 
	"FUNCAO" VARCHAR2(50) NOT NULL ENABLE, 
	 CONSTRAINT "CH_FUNCAO" CHECK (FUNCAO IN ('PRINCIPAL','BANDEIRINHA','RESERVA')) ENABLE, 
	 CONSTRAINT "PK_APITA" PRIMARY KEY ("CPFA", "IDPARTIDA") ENABLE, 
	 CONSTRAINT "FK_APITA_ARBITRO" FOREIGN KEY ("CPFA")
	  REFERENCES "F07_ARBITRO" ("CPFA") ENABLE, 
	 CONSTRAINT "FK_APITA_PARTIDA" FOREIGN KEY ("IDPARTIDA")
	  REFERENCES "F11_PARTIDA" ("IDPARTIDA") ON DELETE CASCADE ENABLE
   ) ;
 

  CREATE TABLE "F14_TRANSMITE" 
   (	"IDEMISSORA" NUMBER(2,0), 
	"IDPARTIDA" NUMBER(4,0), 
	 CONSTRAINT "PK_TRANSMITE" PRIMARY KEY ("IDEMISSORA", "IDPARTIDA") ENABLE, 
	 CONSTRAINT "FK_TRANSMITE_EMISS" FOREIGN KEY ("IDEMISSORA")
	  REFERENCES "F10_EMISSORA" ("IDEMISSORA") ENABLE, 
	 CONSTRAINT "FK_TRANSMITE_PART" FOREIGN KEY ("IDPARTIDA")
	  REFERENCES "F11_PARTIDA" ("IDPARTIDA") ON DELETE CASCADE ENABLE
   ) ;
 

  CREATE TABLE "F15_GOLS_CARTOES" 
   (	"CPFJ" NUMBER(8,0), 
	"IDPARTIDA" NUMBER(4,0), 
	"AMARELO" CHAR(1) DEFAULT 0 NOT NULL ENABLE, 
	"VERMELHO" CHAR(1) DEFAULT 0 NOT NULL ENABLE, 
	"GOLS" NUMBER(2,0) DEFAULT 0 NOT NULL ENABLE, 
	"GOLS_CONTRA" NUMBER(2,0) DEFAULT 0 NOT NULL ENABLE, 
	 CONSTRAINT "CH_CARTOES" CHECK (AMARELO IN (0,1) AND VERMELHO IN (0,1)) ENABLE, 
	 CONSTRAINT "PK_GOLS_CARTOES" PRIMARY KEY ("CPFJ", "IDPARTIDA") ENABLE, 
	 CONSTRAINT "FK_GOLS_CARTOES_JOGADOR" FOREIGN KEY ("CPFJ")
	  REFERENCES "F05_JOGADOR" ("CPFJ") ENABLE, 
	 CONSTRAINT "FK_GOLS_CARTOES_PARTIDA" FOREIGN KEY ("IDPARTIDA")
	  REFERENCES "F11_PARTIDA" ("IDPARTIDA") ENABLE
   ) ;
 
